{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [],
   "source": [
    "from model_selection_utils import *\n",
    "from model_selection import GridSearchCVList\n",
    "from sklearn.linear_model import Lasso, LogisticRegression\n",
    "from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor\n",
    "from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier\n",
    "from sklearn.base import clone\n",
    "from linear_model import WeightedLasso\n",
    "from sklearn.datasets import fetch_california_housing, load_iris\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 69,
   "metadata": {},
   "outputs": [],
   "source": [
    "def reg(models, cv=5):\n",
    "    return GridSearchCVList(models,\n",
    "                             param_grid_list=[{}, {}, {}, {}],\n",
    "                             cv=cv,\n",
    "                             scoring='neg_mean_squared_error')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(10, 1)   (10,)\n"
     ]
    }
   ],
   "source": [
    "X = np.array([0, 1, 2, 3, 4, 5, 6 , 7, 8, 9]).reshape(-1, 1)\n",
    "Y = np.array([0, 2, 4, 6, 8, 10, 12, 14, 16, 18])\n",
    "\n",
    "print(X.shape, \" \", Y.shape)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 52,
   "metadata": {},
   "outputs": [],
   "source": [
    "model = clone(reg().fit(X, Y).best_estimator_)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 56,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "ElasticNetCV()"
      ]
     },
     "execution_count": 56,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "model.fit(X, Y)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 57,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([ 0.02694611,  2.02095808,  4.01497006,  6.00898204,  8.00299401,\n",
       "        9.99700599, 11.99101796, 13.98502994, 15.97904192, 17.97305389])"
      ]
     },
     "execution_count": 57,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "model.predict(X)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 59,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([ 0.02694611,  2.02095808,  4.01497006,  6.00898204,  8.00299401,\n",
       "        9.99700599, 11.99101796, 13.98502994, 15.97904192, 17.97305389])"
      ]
     },
     "execution_count": 59,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "reg().fit(X, Y).predict(X)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 108,
   "metadata": {},
   "outputs": [],
   "source": [
    "# models to compare over (aka every case)\n",
    "model_list = ['linear', 'forest', 'gbf', 'nnet', 'poly', 'automl']\n",
    "models = get_complete_estimator_list(model_list, 'continuous')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 62,
   "metadata": {},
   "outputs": [],
   "source": [
    "import time"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 90,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.\n",
      "  warnings.warn(\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.\n",
      "  warnings.warn(\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.\n",
      "  warnings.warn(\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.\n",
      "  warnings.warn(\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.\n",
      "  warnings.warn(\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.\n",
      "  warnings.warn(\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.\n",
      "  warnings.warn(\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.\n",
      "  warnings.warn(\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.\n",
      "  warnings.warn(\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.\n",
      "  warnings.warn(\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.\n",
      "  warnings.warn(\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.\n",
      "  warnings.warn(\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.\n",
      "  warnings.warn(\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.\n",
      "  warnings.warn(\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.\n",
      "  warnings.warn(\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.\n",
      "  warnings.warn(\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.\n",
      "  warnings.warn(\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.\n",
      "  warnings.warn(\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.\n",
      "  warnings.warn(\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.\n",
      "  warnings.warn(\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.\n",
      "  warnings.warn(\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.\n",
      "  warnings.warn(\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.\n",
      "  warnings.warn(\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "([3.8654184355829573e-31,\n",
       "  0.09130400000000014,\n",
       "  2.3666426423650404e-33,\n",
       "  0.005994299535357941,\n",
       "  2.8398992587956424e-31,\n",
       "  3.8654184355829573e-31],\n",
       " [0.27109503746032715,\n",
       "  0.6357595920562744,\n",
       "  0.0931779146194458,\n",
       "  0.29889988899230957,\n",
       "  0.15522754192352295,\n",
       "  1.2663331031799316])"
      ]
     },
     "execution_count": 90,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "test_models(X, Y, models, iterations=2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 96,
   "metadata": {},
   "outputs": [],
   "source": [
    "\"\"\"\n",
    "Parameters:\n",
    "    X:      explanatory variable\n",
    "    y:      response variable\n",
    "    models: models to search over\n",
    "Returns:\n",
    "    tuple: (mse, time)\n",
    "            mse: average mse over iterations\n",
    "            time: average time to fit over iterations\n",
    "\n",
    "\"\"\"\n",
    "def test_models_helper(X, y, models, iterations=10):\n",
    "    time_diff = []\n",
    "    mse = []\n",
    "    for iters in range(iterations):\n",
    "        curr_time = time.time()\n",
    "        m = reg(models)\n",
    "        m = m.fit(X, y)\n",
    "        curr_time = time.time() - curr_time\n",
    "        mse.append(np.square(np.subtract(y, m.predict(X)).mean()))\n",
    "        time_diff.append(curr_time)\n",
    "\n",
    "    return np.mean(mse), np.mean(time_diff)\n",
    "\n",
    "\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 89,
   "metadata": {},
   "outputs": [],
   "source": [
    "\"\"\"\n",
    "Parameters:\n",
    "    X:      explanatory variable\n",
    "    y:      response variable\n",
    "    models: models to search over\n",
    "    iterations: number of iterations to average over\n",
    "    test_all: whether or not to test all the models at once\n",
    "\n",
    "Returns:\n",
    "    tuple: (mse array, time array)\n",
    "            mse: average mse over iterations for every model\n",
    "            time: average time to fit over iterations for every model\n",
    "            NOTE: if test_all then last elements of returned arrays is all models mse and time\n",
    "\n",
    "\"\"\"\n",
    "def test_models(X, y, models, iterations=10, test_all=True):\n",
    "    time_diff = []\n",
    "    mse = []\n",
    "    # test every individual model\n",
    "    for m in models:\n",
    "        mse_temp, time_diff_temp = test_models_helper(X, y, [m], iterations)\n",
    "        mse.append(mse_temp)\n",
    "        time_diff.append(time_diff_temp)\n",
    "    # test all\n",
    "    if test_all:\n",
    "        mse_temp, time_diff_temp = test_models_helper(X, y, models, iterations)\n",
    "        mse.append(mse_temp)\n",
    "        time_diff.append(time_diff_temp)   \n",
    "    return mse, time_diff\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [],
   "source": [
    "X_cali, y_cali = fetch_california_housing(return_X_y=True)\n",
    "#print(X_cali.shape, y_cali.shape)\n",
    "#mse_out, time_out = test_models(X_cali, y_cali, models, iterations=1)\n",
    "\n",
    "training_data = X_cali"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 110,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAtQAAAHlCAYAAADV42tlAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjQuMywgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/MnkTPAAAACXBIWXMAAAsTAAALEwEAmpwYAAAdwklEQVR4nO3df5RkZ13n8c/XTJgJJJkkkwkGBpmoQWTFDToqGBAQEH+gxGM4ApKTIBp/k3j0uLMumMFfZ1CBuB5ZDb8yCAsLgd3ErAIhGLNCiJlAJIQAIwhhIMIwxpEE0knk2T/qthRDz0xPP91V3T2v1zl96tatW1VP56a633P7qVvVWgsAALAwXzftAQAAwEomqAEAoIOgBgCADoIaAAA6CGoAAOggqAEAoMOaaQ9goU4++eS2efPmaQ8DAIBV7sYbb/x8a23jgW5fsUG9efPm7Ny5c9rDAABglauqTx7sdlM+AACgg6AGAIAOghoAADqs2DnUc7n33nuze/fu3H333dMeyrysW7cumzZtytFHHz3toQAAsECrKqh3796d4447Lps3b05VTXs4B9Vay969e7N79+6cdtpp0x4OAAALtKqmfNx9993ZsGHDso/pJKmqbNiwYcUcTQcAYG6rKqiTrIiYnrWSxgoAwNxW1ZSP5eDYY4/Nddddl3POOSdJctttt2X9+vVZv359Tj755Lzzne+c8ggBAFhMqzqoL96+PftmZhbt8davXZsLt2495HaPfOQjc9NNNyVJzjvvvDztaU/L2WefvWjjAABg+VjVQb1vZiYXbdu2aI/3okV8LAAAVodVN4caAAAmSVADAEAHQQ0AAB0ENQAAdBDUAADQYVWf5WP92rWLemaO9WvXHnKbO++886uuX3rppYv2/AAALD+rOqjnc85oAADoYcoHAAB0ENQAANBh1U35aK2lqqY9jHlprU17CAAAh+3i7duzb2Zmos+5fu3aZTudd1UF9bp167J3795s2LBh2Ud1ay179+7NunXrpj0UAIDDsm9mJhct4okf5mMxTzSx2FZVUG/atCm7d+/Onj17pj2UeVm3bl02bdo07WEAANBhVQX10UcfndNOO23awwAA4AjiTYkAANBBUAMAQAdBDQAAHQQ1AAB0ENQAANBBUAMAQAdBDQAAHQQ1AAB0ENQAANBBUAMAQAdBDQAAHQQ1AAB0ENQAANBBUAMAQAdBDQAAHQQ1AAB0ENQAANBBUAMAQAdBDQAAHQQ1AAB0ENQAANBBUAMAQAdBDQAAHQQ1AAB0ENQAANBBUAMAQAdBDQAAHQQ1AAB0ENQAANBBUAMAQAdBDQAAHQQ1AAB0ENQAANBBUAMAQAdBDQAAHQQ1AAB0ENQAANBBUAMAQAdBDQAAHQQ1AAB0ENQAANBBUAMAQAdBDQAAHQQ1AAB0ENQAANBBUAMAQAdBDQAAHQQ1AAB0ENQAANBBUAMAQAdBDQAAHQQ1AAB0ENQAANBh4kFdVb9aVbdU1Qer6g1Vta6qTqqqq6pq13B54qTHBQAACzHRoK6qByd5fpItrbVvS3JUkmcm2Zrk6tba6UmuHq4DAMCyN40pH2uSHFNVa5LcP8lnkjw9yY7h9h1JzprCuAAA4LBNNKhba59O8kdJbktye5J9rbV3JHlga+32YZvbk5wyyXEBAMBCTXrKx4kZHY0+LcmDkjygqp5zGPc/v6p2VtXOPXv2LNUwAQBg3iY95ePJSf6ptbantXZvkrcm+d4kn62qU5NkuPzcXHdurV3SWtvSWtuycePGiQ0aAAAOZNJBfVuSR1fV/auqkjwpya1Jrkhy7rDNuUkun/C4AABgQdZM8slaa9dX1WVJ3pfkviTvT3JJkmOTvKmqnpdRdD9jkuMCAICFmmhQJ0lr7aIkF+23eiajo9UAALCi+KREAADoIKgBAKCDoAYAgA6CGgAAOghqAADoIKgBAKCDoAYAgA6CGgAAOghqAADoIKgBAKCDoAYAgA6CGgAAOghqAADoIKgBAKCDoAYAgA6CGgAAOghqAADoIKgBAKCDoAYAgA6CGgAAOghqAADoIKgBAKCDoAYAgA6CGgAAOghqAADoIKgBAKCDoAYAgA6CGgAAOghqAADoIKgBAKCDoAYAgA6CGgAAOghqAADoIKgBAKCDoAYAgA6CGgAAOghqAADoIKgBAKCDoAYAgA6CGgAAOghqAADoIKgBAKCDoAYAgA6CGgAAOghqAADoIKgBAKCDoAYAgA6CGgAAOghqAADoIKgBAKCDoAYAgA6CGgAAOghqAADoIKgBAKCDoAYAgA6CGgAAOghqAADoIKgBAKCDoAYAgA6CGgAAOghqAADoIKgBAKCDoAYAgA6CGgAAOghqAADoIKgBAKCDoAYAgA6CGgAAOghqAADoIKgBAKCDoAYAgA6CGgAAOghqAADoIKgBAKCDoAYAgA6CGgAAOghqAADoIKgBAKCDoAYAgA4TD+qqOqGqLquqD1fVrVX1mKo6qaquqqpdw+WJkx4XAAAsxDSOUP9xkre11h6e5D8nuTXJ1iRXt9ZOT3L1cB0AAJa9iQZ1VR2f5PuSvCpJWmv3tNb+NcnTk+wYNtuR5KxJjgsAABZq0keovzHJniSvqar3V9Urq+oBSR7YWrs9SYbLUyY8LgAAWJBJB/WaJN+R5H+01h6V5K4cxvSOqjq/qnZW1c49e/Ys1RgBAGDeJh3Uu5Psbq1dP1y/LKPA/mxVnZokw+Xn5rpza+2S1tqW1tqWjRs3TmTAAABwMBMN6tbaPyf5VFV9y7DqSUk+lOSKJOcO685NcvkkxwUAAAu1ZgrP+StJXl9V90vy8STPzSjs31RVz0tyW5JnTGFcAABw2CYe1K21m5JsmeOmJ014KAAA0M0nJQIAQAdBDQAAHaYxhxqWjYu3b8++mZmJPuf6tWtz4VYfBgoAq4Wg5oi2b2YmF23bNtHnfNGEnw8AWFqmfAAAQAdBDQAAHQQ1AAB0ENQAANBBUAMAQAdBDQAAHQQ1AAB0ENQAANBBUAMAQAdBDQAAHQQ1AAB0ENQAANBBUAMAQAdBDQAAHQQ1AAB0ENQAANBBUAMAQAdBDQAAHQQ1AAB0ENQAANBBUAMAQAdBDQAAHQQ1AAB0ENQAANBBUAMAQIdDBnVV/VNVfWy/dS+tqpfst+7LVXXfYg8QAACWszXz2OahSdp+6y4c1v3afutrEcYEAAArhikfAADQQVADAECH+Uz5SJJU1UOy35SOudYBAMCRZN5BneQTY8ttjnUAAHDEOZygdiQaAAD2M5+gvjZfe5YPAAAg8wjq1toTJjAOAABYkZzlAwAAOhzyCHVVVZKjk7TW2r1j65+R5OlJTkrykSQvb63tWqqBAgDAcjSfI9QXJ/lSkjfPrqiqrUnemORZSZ6a5PlJbqyqMxZ/iAAAsHzNJ6i/c7j8iySpqnVJtmZ01o/xr2OTvGAJxggAAMvWfIL6tOHyhuHycUmOz+jMH9cNy7843PbYRR0dAAAsc/MJ6pOGy9uHy8eN3fbnrbU7k+wYrp+4WAMDAICVYD5B/S/D5TcPlz84dtvVw+VRw+W/LsKYAABgxZjPB7vcnOTrk1xZVR9NsiWj6R43ttY+PWwzO8/69jnuDwAAq9Z8jlD/dkYBfVqSHxhb/3tjy88eLt+9SOMCAIAV4ZBB3Vp7T5IfSvKOJLuSXJPkma21y5Okqo5N8i1Jrk/yliUbKQAALEPzmfKR1tpVSa46wG13JnnCIo4JAABWjPl8UuIlh/F4rbX2cx3jAQCAFWU+R6h/JqM51PMlqAEAOGLMa8rHoOaxzeGENwAArHjzDerKKJZvS/KaJG9O8sWlGhQAAKwU8zlt3pkZRfRdSR6a5KKMPnJ8a5KNrbVPjn8t3VABAGD5mc9p865rrT0vyalJfjaj0+Mdn+T8JNdX1c1V9ZNLO0wAAFie5nOEOknSWrurtfaq1tr3JnlaRh8zXkkekURQAwBwRJr3mxKram2Sn0jy0xmdd3o2xncluWzRRwYAACvAfM5D/R1JnpfkWUnWZ3RU+q6M3pj4qtaajxsHAOCINZ8j1DszOsNHJflkkkuTvDHJF5Kkqh40vnFr7TOLO0QAAFi+Duc81C3JNyT5reHrQNsczmMCAMCKdjjnoQYAAPYzn6DeseSjAACAFeqQQd1ae+4kBgIAACvRvM9DDQAAfC1BDQAAHQQ1AAB0ENQAANBBUAMAQAdBDQAAHQQ1AAB0ENQAANBBUAMAQAdBDQAAHQQ1AAB0ENQAANBBUAMAQAdBDQAAHQQ1AAB0ENQAANBBUAMAQIepBHVVHVVV76+qK4frJ1XVVVW1a7g8cRrjAgCAwzWtI9QXJLl17PrWJFe31k5PcvVwHQAAlr2JB3VVbUryI0leObb66Ul2DMs7kpw14WEBAMCCTOMI9cVJfiPJl8fWPbC1dnuSDJenzHXHqjq/qnZW1c49e/Ys+UABAOBQJhrUVfW0JJ9rrd24kPu31i5prW1prW3ZuHHjIo8OAAAO35oJP9+ZSX6sqn44ybokx1fV65J8tqpOba3dXlWnJvnchMcFAAALMtEj1K21/9pa29Ra25zkmUne1Vp7TpIrkpw7bHZukssnOS4AAFio5XIe6u1JnlJVu5I8ZbgOAADL3qSnfPyH1to1Sa4ZlvcmedK0xgIAAAu1XI5QAwDAiiSoAQCgg6AGAIAOghoAADoIagAA6CCoAQCgg6AGAIAOghoAADoIagAA6CCoAQCgg6AGAIAOghoAADoIagAA6CCoAQCgg6AGAIAOghoAADoIagAA6CCoAQCgg6AGAIAOghoAADoIagAA6CCoAQCgg6AGAIAOghoAADoIagAA6CCoAQCgg6AGAIAOghoAADoIagAA6CCoAQCgg6AGAIAOghoAADoIagAA6CCoAQCgg6AGAIAOghoAADoIagAA6CCoAQCgg6AGAIAOghoAADoIagAA6CCoAQCgg6AGAIAOghoAADoIagAA6CCoAQCgg6AGAIAOghoAADoIagAA6CCoAQCgg6AGAIAOghoAADoIagAA6CCoAQCgw5ppDwBgsVy8fXv2zcxM9DnXr12bC7dunehzArC8CGpg1dg3M5OLtm2b6HO+aMLPB8DyY8oHAAB0ENQAANBBUAMAQAdBDQAAHQQ1AAB0ENQAANBBUAMAQAdBDQAAHQQ1AAB0ENQAANBBUAMAQAdBDQAAHQQ1AAB0ENQAANBBUAMAQAdBDQAAHQQ1AAB0ENQAANBBUAMAQAdBDQAAHQQ1AAB0ENQAANBBUAMAQIeJBnVVPaSq/qaqbq2qW6rqgmH9SVV1VVXtGi5PnOS4AABgoSZ9hPq+JL/WWvvWJI9O8ktV9YgkW5Nc3Vo7PcnVw3UAAFj2JhrUrbXbW2vvG5a/kOTWJA9O8vQkO4bNdiQ5a5LjAgCAhZraHOqq2pzkUUmuT/LA1trtySi6k5wyrXEBAMDhmEpQV9WxSd6S5MLW2r8dxv3Or6qdVbVzz549SzdAAACYp4kHdVUdnVFMv7619tZh9Wer6tTh9lOTfG6u+7bWLmmtbWmtbdm4ceNkBgwAAAcx6bN8VJJXJbm1tfbSsZuuSHLusHxukssnOS4AAFioNRN+vjOTnJPk5qq6aVj3m0m2J3lTVT0vyW1JnjHhcQEAwIJMNKhba3+XpA5w85MmORYAAFgMPikRAAA6CGoAAOggqAEAoIOgBgCADoIaAAA6CGoAAOggqAEAoIOgBgCADoIaAAA6CGoAAOggqAEAoIOgBgCADoIaAAA6CGoAAOggqAEAoIOgBgCADoIaAAA6CGoAAOggqAEAoIOgBgCADoIaAAA6CGoAAOggqAEAoIOgBgCADoIaAAA6CGoAAOiwZtoDAIC5XLx9e/bNzEz0OdevXZsLt26d6HMCK5+gBmBZ2jczk4u2bZvoc75ows8HrA6mfAAAQAdBDQAAHQQ1AAB0ENQAANBBUAMAQAdBDQAAHQQ1AAB0ENQAANBBUAMAQAdBDQAAHQQ1AAB0ENQAANBBUAMAQAdBDQAAHQQ1AAB0ENQAANBBUAMAQAdBDQAAHQQ1AAB0ENQAANBBUAMAQAdBDQAAHQQ1AAB0ENQAANBBUAMAQAdBDQAAHQQ1AAB0ENQAANBBUAMAQAdBDQAAHQQ1AAB0ENQAANBBUAMAQAdBDQAAHQQ1AAB0ENQAANBBUAMAQAdBDQAAHQQ1AAB0ENQAANBBUAMAQAdBDQAAHdZMewAAwOp38fbt2TczM9HnXL92bS7cunWiz8mRSVADAEtu38xMLtq2baLP+aIJPx9HLlM+AACgg6AGAIAOghoAADoIagAA6CCoAQCgg6AGAIAOghoAADosm/NQV9UPJvnjJEcleWVrbfuUhzQnJ6YHAGDcsgjqqjoqyZ8meUqS3UluqKorWmsfmu7IvpYT0wMAMG65TPn47iT/2Fr7eGvtniRvTPL0KY8JAAAOabkE9YOTfGrs+u5hHQAALGvVWpv2GFJVz0jy1NbazwzXz0ny3a21X9lvu/OTnD9c/ZYkH5noQFemk5N8ftqDYNHYn6uL/bm62J+ri/25uvTuz4e21jYe6MZlMYc6oyPSDxm7vinJZ/bfqLV2SZJLJjWo1aCqdrbWtkx7HCwO+3N1sT9XF/tzdbE/V5el3p/LZcrHDUlOr6rTqup+SZ6Z5IopjwkAAA5pWRyhbq3dV1W/nOTtGZ0279WttVumPCwAADikZRHUSdJa+6skfzXtcaxCpsisLvbn6mJ/ri725+pif64uS7o/l8WbEgEAYKVaLnOoAQBgRRLUK0hV3TlcPqiqLpv2eOhTVc+vqlur6vVL8Nibq+rZi/24LI6quqaqvubd5lW1tqreWVU3VdVPTmNsLA2vyZXrQK9Xlq+qOquqHrGIj3fnobYR1CtQa+0zrbWzl/I5qmrZzK9fxX4xyQ+31n7qUBsuYH9sTuKX98rzqCRHt9bOaK39r2kPhkW1OV6TMClnJVm0oJ4PQb0CDUc6Pjgsn1dVb62qt1XVrqr6g7HtfqCqrquq91XVm6vq2GH9b1XVDVX1waq6pKpqWH9NVf1+Vf1tkgum8s0dIarqz5J8Y5IrqurXqur/VNUHquq9VfXtwzbbhv3zjiSvraqNVfWWYd/dUFVnDts9fjiieVNVvb+qjkuyPcnjhnW/OrVvlFTVC6vqw1V1VVW9oap+fbjpOVX1nuF1+N1VdUqS1yU5Y9hv3zTFYTMYft7eWlWvqKpbquodVXXM8PPyxVX191X10ap63LD9UVX1h8Nr9ANV9XPDQ3lNLhPDPv1wVe0Y9tFlVXX/qnrS8DP05qp6dVWt3e9+z6uql41d/9mqeunkv4Mj0/B78sbhdXj+sO7OsdvPrqpLq+p7k/xYkj+c/VlaVWcMv18/UFX/u6pOHO5zTVW9rKquHV7n3zU01a6q+t3DGmBrzdcK+Upy53C5OckHh+Xzknw8yfok65J8MqMPyTk5ybVJHjBs91+S/NawfNLYY/5Fkh8dlq9J8vJpf59HyleSTwz76U+SXDSs+/4kNw3L25LcmOSY4fr/TPLYYfkbktw6LP9lkjOH5WMzOnvPE5JcOe3v8Uj/SrIlyU1JjklyXJJdSX59eK29Ytjm+8Zez/bbMvsaft7el+SM4fqbkjxn2IcvGdb9cJJ3DsvnJ3nBsLw2yc4kp9m3y+dr2Kdt7Ofmq5O8IMmnkjxsWPfaJBcOy9cMr+UHJPlYRn9FSpL3JHnktL+fI+Vrtl2Gn6cfTLJhtouG9WcnuXRYvjTJ2WO3fSDJ44fl305y8di+ffGwfEFGHyp46vDa3Z1kw3DbnYcanz/rrw5Xt9b2JUlVfSjJQ5OckNGfO949HIC+X5Lrhu2fWFW/keT+SU5KcktGUZYk/sw8eY9N8hNJ0lp7V1VtqKr1w21XtNa+NCw/Ockjhv2ZJMcPR6PfneSlNZqL/dbW2u6xbZiuxya5fHYfVtVfjt32hiRprV1bVcdX1QlTGB/z80+ttZuG5RszCrIkeesc634gybdX1ey0vPVJTk9yz5KPksPxqdbau4fl1yV5YUb7+aPDuh1JfinJxbN3aK3dVVXvSvK0qro1o7C+eYJjPtI9v6p+fFh+SEavq0Mafp+e0Fr722HVjiRvHttk9oMEb05yS2vt9uF+Hx+eZ+98nkdQrw4zY8v/ntF+rSRXtdaeNb5hVa1L8vIkW1prn6qqbRkd2Z511xKPla81V/3Ons9yfH98XZLHjAX2rO1V9X8zOkr23qp68hKMkYU52L9s9j9nqXOYLl/7/4w9Zr/1sz93k9E+/5XW2tvHH6CqnrCE4+PwLfT19sokv5nkw0les3jD4WCG18+TM/od+MWquiajdhnfj+u+9p7zMvs6/nK++rX+5RxGJ5tDvXq9N8mZVfXNSTLMD3tYvvI/3OdrNKd6Sd/cyLxcm+Snkv/4ofH51tq/zbHdO5L88uyVqjpjuPym1trNrbUXZ/Tn5Ycn+UJGUwyYrr9L8qNVtW54vf3I2G0/mSRV9dgk+2b/ysSK9/Ykv1BVRydJVT2sqh4Qr8nl5huq6jHD8rOSvDPJ5tnfmUnOSfK3+9+ptXZ9Rkctn53hr0xMxPokdwwx/fAkjx7Wf7aqvrWqvi7Jj49t/x+vt+Fn6x2z73PIAfZtL0eoV6nW2p6qOi/JG8beWPGC1tpHq+oVGf1p4xNJbpjSEPmKbUleU1UfSPLFJOceYLvnJ/nTYbs1GYX4zye5sKqemNFRsg8l+euM/mV9X1X9Q0Zzyl52gMdkCbXWbqiqK5L8Q0bvb9iZZDac76iq9yQ5PslPT2mILL5XZjT94301mnu1J6MzDnwgXpPLya1Jzq2qP8/ovQ0XZHQg6s01OqvSDUn+7AD3fVNGc+rvmMhISZK3Jfn54fffRzLaV0myNcmVGc1//2BG7yNKkjcmeUVVPT+jA4fnJvmzqrp/Ru87e+5iD9AnJQIsoao6trV25/CD/Nok57fW3jftccGRqqo2Z/QG0W9b4P2vTPKy1trVizowVjRTPgCW1iVVdVOS9yV5i5iGlamqTqiqjyb5kphmf45QAwBAB0eoAQCgg6AGAIAOghoAADoIaoAjTFWdV1Vt+HrCAu4/e99LF31wACuQoAYAgA6CGgAAOghqgCmpqmuGqROfqKqnVtWHquqLVXVlVZ1SVWdU1XVVdVdVXV9V3zl232Oq6neq6iNVNVNVd1TV24aPMh9/jvtX1SVVta+q9lbVy5Lc7wDjOaGqXlJVH6uqe6pqT1W9sapOn8f38uSq+pvhPjNV9elhPGf1/ncCWO6chxpgSqrqmiSPT3JXRh8nv3bs5ncneXiSDWPrPpXkm4bldyX5qnge/HuSs1prVw7P8dok5+y3zT8n+fph+YmttWuq6rgk1yX5T3M85h1Jvqe1tmt4zNlfHDtaa+dV1UOTfDjJujnu+6ettV+eYz3AquEINcD0PSDJi5OckOTvhnVnJvn7JCcluXhY95Ak35Pkp/KVmH79sM3jk9yZ5Kgkf1IjDxu2TZL3D/f/tiT3zTGGCzOK6XuS/GBGcfzIJJ9LcmKS3znI+LfkKzH9XRn9w+ChSZ499v0ArFqCGmD67kmyvbW2L6Mj07P+qLV2R5K/Hlv3kCRPHbv+31prd7TWrk1y2bBuc5LTkzw6X/k5/7LW2u7W2i1JXj3HGH5ouLxfkrcluTvJzUlOGdY/8SDj/+TY8m8m+aWMjq5f2Vp740HuB7AqCGqA6dvTWvvSsHz32Prbhst7xtatTXLy2PXdB1jemOTUseufHlv+zBxj2HiIMZ50oBtaazuT/F6SLyX58SQvTfL2JJ+tqp85xOMCrHiCGmD65pqCcbD1nx9bfvDY8qb9trn9ANs96CCPuTfJUa21Gv/KAd7IOKu19oKMQv/MJOcleW+SY5L896pac7D7Aqx0ghpg5XnH2PLvDmfneGySnxjWfTLJRzN6k+GXh3W/WlUPrqpHJPnpOR7zbcPlhiQvraqThzOJfE9VvTrJ1gMNpqoeWVUvTPKwJLdkNPXk/cPNxyQ57vC/RYCVQ1ADrDyvyyiWk9EZPO5I8v8yCtd/T3JBG9mV0ZsWk+RRGU0JuSWjyN3fxRmdqSNJLkiyJ8kXMzrS/Nx89RlI9rchyW9nFNH/mtGbI39huO36YR44wKolqAFWmNbavUmenOT3k/xjknuT7MvoyPX3t9YuH9v8F5K8MskXMgrvlyd54RyPuS/JY5K8JMnHMpq3/S9JbsxofvRrDzKkf0xySUaxvi/JTJJPDOvOWtA3CbCCOA81AAB0cIQaAAA6CGoAAOggqAEAoIOgBgCADoIaAAA6CGoAAOggqAEAoIOgBgCADoIaAAA6/H89ltdmGBSMXAAAAABJRU5ErkJggg==",
      "text/plain": [
       "<Figure size 864x576 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    " \n",
    "# set width of bar\n",
    "barWidth = 0.25\n",
    "fig = plt.subplots(figsize =(12, 8))\n",
    " \n",
    "# set height of bar\n",
    "#IT = [12, 30, 1, 8, 22]\n",
    "#ECE = [28, 6, 16, 5, 10]\n",
    "#CSE = [29, 3, 24, 25, 17]\n",
    " \n",
    "# Set position of bar on X axis\n",
    "br1 = np.arange(len(mse_out))\n",
    "br2 = [x + barWidth for x in br1]\n",
    "#br3 = [x + barWidth for x in br2]\n",
    " \n",
    "# Make the plot\n",
    "plt.bar(br1, time_out, color ='r', width = barWidth,\n",
    "        edgecolor ='grey', label ='IT')\n",
    "#plt.bar(br2, time_out, color ='g', width = barWidth,\n",
    "        #edgecolor ='grey', label ='ECE')\n",
    "#plt.bar(br3, CSE, color ='b', width = barWidth,\n",
    "        #edgecolor ='grey', label ='CSE')\n",
    " \n",
    "# Adding Xticks\n",
    "plt.xlabel('models', fontweight ='bold', fontsize = 15)\n",
    "plt.ylabel('MSE', fontweight ='bold', fontsize = 15)\n",
    "plt.xticks([r + barWidth for r in range(len(mse_out))],\n",
    "        [*model_list])\n",
    " \n",
    "plt.legend()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 114,
   "metadata": {},
   "outputs": [],
   "source": [
    "# pip install hyperopt\n",
    "import hyperopt as hp"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 118,
   "metadata": {},
   "outputs": [],
   "source": [
    "#X_cali, y_cali\n",
    "#X_cali[-100:].shape\n",
    "# train on all except last 100\n",
    "training_data = X_cali[:-100], y_cali[:-100]\n",
    "testing_data = X_cali[-100:], y_cali[-100:]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def objective(hyperparameters):\n",
    "    \"\"\"Returns validation score from hyperparameters\"\"\"\n",
    "    \n",
    "    model = Classifier(hyperparameters)\n",
    "    validation_loss = cross_validation(model, training_data)    \n",
    "    return validation_loss\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting package metadata (current_repodata.json): done\n",
      "Solving environment: | \n",
      "The environment is inconsistent, please check the package plan carefully\n",
      "The following packages are causing the inconsistency:\n",
      "\n",
      "  - defaults/noarch::sphinx==4.2.0=pyhd3eb1b0_1\n",
      "  - defaults/noarch::numpydoc==1.1.0=pyhd3eb1b0_1\n",
      "  - defaults/osx-64::anaconda==2021.11=py39_0\n",
      "  - defaults/osx-64::spyder==5.1.5=py39hecd8cb5_1\n",
      "| ^C\n",
      "failed with initial frozen solve. Retrying with flexible solve.\n",
      "\n",
      "CondaError: KeyboardInterrupt\n",
      "\n",
      "\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "conda install -c conda-forge bayesian-optimization\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting colorama==0.4.6\n",
      "  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)\n",
      "Installing collected packages: colorama\n",
      "  Attempting uninstall: colorama\n",
      "    Found existing installation: colorama 0.4.4\n",
      "    Uninstalling colorama-0.4.4:\n",
      "      Successfully uninstalled colorama-0.4.4\n",
      "Successfully installed colorama-0.4.6\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install -U colorama==0.4.6"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "from bayes_opt import BayesianOptimization"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [],
   "source": [
    "from bayes_opt import BayesianOptimization\n",
    "from scipy.stats import uniform\n",
    "from sklearn.model_selection import cross_val_score\n",
    "from sklearn.ensemble import GradientBoostingClassifier\n",
    "from sklearn.model_selection import GridSearchCV"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "|   iter    |  target   | learni... | max_depth | max_fe... | n_esti... | subsample |\n",
      "-------------------------------------------------------------------------------------\n",
      "| \u001b[0m1        \u001b[0m | \u001b[0mnan      \u001b[0m | \u001b[0m0.616    \u001b[0m | \u001b[0m4.183    \u001b[0m | \u001b[0m0.8872   \u001b[0m | \u001b[0m133.8    \u001b[0m | \u001b[0m0.8591   \u001b[0m |\n",
      "| \u001b[0m2        \u001b[0m | \u001b[0mnan      \u001b[0m | \u001b[0m0.1577   \u001b[0m | \u001b[0m3.157    \u001b[0m | \u001b[0m0.884    \u001b[0m | \u001b[0m96.71    \u001b[0m | \u001b[0m0.8675   \u001b[0m |\n",
      "| \u001b[0m3        \u001b[0m | \u001b[0mnan      \u001b[0m | \u001b[0m0.9908   \u001b[0m | \u001b[0m4.664    \u001b[0m | \u001b[0m0.8162   \u001b[0m | \u001b[0m126.9    \u001b[0m | \u001b[0m0.9242   \u001b[0m |\n",
      "| \u001b[0m4        \u001b[0m | \u001b[0mnan      \u001b[0m | \u001b[0m0.2815   \u001b[0m | \u001b[0m6.264    \u001b[0m | \u001b[0m0.8237   \u001b[0m | \u001b[0m85.18    \u001b[0m | \u001b[0m0.9802   \u001b[0m |\n",
      "| \u001b[0m5        \u001b[0m | \u001b[0mnan      \u001b[0m | \u001b[0m0.796    \u001b[0m | \u001b[0m8.884    \u001b[0m | \u001b[0m0.963    \u001b[0m | \u001b[0m149.4    \u001b[0m | \u001b[0m0.9155   \u001b[0m |\n",
      "| \u001b[0m6        \u001b[0m | \u001b[0mnan      \u001b[0m | \u001b[0m0.8156   \u001b[0m | \u001b[0m5.949    \u001b[0m | \u001b[0m0.8055   \u001b[0m | \u001b[0m111.8    \u001b[0m | \u001b[0m0.8211   \u001b[0m |\n",
      "| \u001b[0m7        \u001b[0m | \u001b[0mnan      \u001b[0m | \u001b[0m0.819    \u001b[0m | \u001b[0m7.884    \u001b[0m | \u001b[0m0.9131   \u001b[0m | \u001b[0m99.2     \u001b[0m | \u001b[0m0.9997   \u001b[0m |\n",
      "| \u001b[0m8        \u001b[0m | \u001b[0mnan      \u001b[0m | \u001b[0m0.1467   \u001b[0m | \u001b[0m7.308    \u001b[0m | \u001b[0m0.897    \u001b[0m | \u001b[0m108.4    \u001b[0m | \u001b[0m0.9456   \u001b[0m |\n",
      "| \u001b[0m9        \u001b[0m | \u001b[0mnan      \u001b[0m | \u001b[0m0.3296   \u001b[0m | \u001b[0m5.804    \u001b[0m | \u001b[0m0.8638   \u001b[0m | \u001b[0m146.3    \u001b[0m | \u001b[0m0.9837   \u001b[0m |\n",
      "| \u001b[0m10       \u001b[0m | \u001b[0mnan      \u001b[0m | \u001b[0m0.8157   \u001b[0m | \u001b[0m3.239    \u001b[0m | \u001b[0m0.9887   \u001b[0m | \u001b[0m146.5    \u001b[0m | \u001b[0m0.9613   \u001b[0m |\n",
      "| \u001b[0m11       \u001b[0m | \u001b[0mnan      \u001b[0m | \u001b[0m0.4865   \u001b[0m | \u001b[0m9.767    \u001b[0m | \u001b[0m0.8834   \u001b[0m | \u001b[0m102.3    \u001b[0m | \u001b[0m0.8033   \u001b[0m |\n",
      "| \u001b[0m12       \u001b[0m | \u001b[0mnan      \u001b[0m | \u001b[0m0.0478   \u001b[0m | \u001b[0m3.372    \u001b[0m | \u001b[0m0.8256   \u001b[0m | \u001b[0m82.34    \u001b[0m | \u001b[0m0.8453   \u001b[0m |\n",
      "| \u001b[0m13       \u001b[0m | \u001b[0mnan      \u001b[0m | \u001b[0m0.5485   \u001b[0m | \u001b[0m4.25     \u001b[0m | \u001b[0m0.8359   \u001b[0m | \u001b[0m90.47    \u001b[0m | \u001b[0m0.9366   \u001b[0m |\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "| \u001b[0m14       \u001b[0m | \u001b[0mnan      \u001b[0m | \u001b[0m0.4743   \u001b[0m | \u001b[0m8.378    \u001b[0m | \u001b[0m0.9338   \u001b[0m | \u001b[0m110.9    \u001b[0m | \u001b[0m0.919    \u001b[0m |\n",
      "| \u001b[0m15       \u001b[0m | \u001b[0mnan      \u001b[0m | \u001b[0m0.467    \u001b[0m | \u001b[0m9.743    \u001b[0m | \u001b[0m0.8296   \u001b[0m | \u001b[0m143.5    \u001b[0m | \u001b[0m0.8996   \u001b[0m |\n",
      "| \u001b[0m16       \u001b[0m | \u001b[0mnan      \u001b[0m | \u001b[0m0.5966   \u001b[0m | \u001b[0m7.793    \u001b[0m | \u001b[0m0.8355   \u001b[0m | \u001b[0m140.5    \u001b[0m | \u001b[0m0.8964   \u001b[0m |\n",
      "| \u001b[0m17       \u001b[0m | \u001b[0mnan      \u001b[0m | \u001b[0m0.07865  \u001b[0m | \u001b[0m5.553    \u001b[0m | \u001b[0m0.8723   \u001b[0m | \u001b[0m113.0    \u001b[0m | \u001b[0m0.8359   \u001b[0m |\n",
      "| \u001b[0m18       \u001b[0m | \u001b[0mnan      \u001b[0m | \u001b[0m0.1835   \u001b[0m | \u001b[0m9.644    \u001b[0m | \u001b[0m0.9311   \u001b[0m | \u001b[0m89.45    \u001b[0m | \u001b[0m0.9856   \u001b[0m |\n",
      "| \u001b[0m19       \u001b[0m | \u001b[0mnan      \u001b[0m | \u001b[0m0.8434   \u001b[0m | \u001b[0m3.369    \u001b[0m | \u001b[0m0.8407   \u001b[0m | \u001b[0m141.1    \u001b[0m | \u001b[0m0.9348   \u001b[0m |\n",
      "| \u001b[0m20       \u001b[0m | \u001b[0mnan      \u001b[0m | \u001b[0m0.3043   \u001b[0m | \u001b[0m8.141    \u001b[0m | \u001b[0m0.9237   \u001b[0m | \u001b[0m94.73    \u001b[0m | \u001b[0m0.9604   \u001b[0m |\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/model_selection/_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 423, in fit\n",
      "    y = self._validate_y(y, sample_weight)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_gb.py\", line 1103, in _validate_y\n",
      "    check_classification_targets(y)\n",
      "  File \"/Users/coopergibbs/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/multiclass.py\", line 183, in check_classification_targets\n",
      "    raise ValueError(\"Unknown label type: %r\" % y_type)\n",
      "ValueError: Unknown label type: 'continuous'\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n"
     ]
    },
    {
     "ename": "ValueError",
     "evalue": "Input contains NaN, infinity or a value too large for dtype('float64').",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mStopIteration\u001b[0m                             Traceback (most recent call last)",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.9/site-packages/bayes_opt/bayesian_optimization.py\u001b[0m in \u001b[0;36mmaximize\u001b[0;34m(self, init_points, n_iter, acquisition_function, acq, kappa, kappa_decay, kappa_decay_delay, xi, **gp_params)\u001b[0m\n\u001b[1;32m    305\u001b[0m             \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 306\u001b[0;31m                 \u001b[0mx_probe\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mnext\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_queue\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    307\u001b[0m             \u001b[0;32mexcept\u001b[0m \u001b[0mStopIteration\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.9/site-packages/bayes_opt/bayesian_optimization.py\u001b[0m in \u001b[0;36m__next__\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m     26\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mempty\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 27\u001b[0;31m             \u001b[0;32mraise\u001b[0m \u001b[0mStopIteration\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Queue is empty, no more objects to retrieve.\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     28\u001b[0m         \u001b[0mobj\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_queue\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;36m0\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mStopIteration\u001b[0m: Queue is empty, no more objects to retrieve.",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "\u001b[0;32m/var/folders/k3/_2yz9lmn4qq33cbwhzsf9h8c0000gn/T/ipykernel_74018/4175922661.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m     21\u001b[0m }\n\u001b[1;32m     22\u001b[0m \u001b[0mgbm_bo\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mBayesianOptimization\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mgbm_cl_bo\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mparams_gbm\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mrandom_state\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m111\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 23\u001b[0;31m \u001b[0mgbm_bo\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mmaximize\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0minit_points\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m20\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mn_iter\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m4\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     24\u001b[0m \u001b[0;31m#print('It takes %s minutes' % ((time.time() - start)/60))\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.9/site-packages/bayes_opt/bayesian_optimization.py\u001b[0m in \u001b[0;36mmaximize\u001b[0;34m(self, init_points, n_iter, acquisition_function, acq, kappa, kappa_decay, kappa_decay_delay, xi, **gp_params)\u001b[0m\n\u001b[1;32m    307\u001b[0m             \u001b[0;32mexcept\u001b[0m \u001b[0mStopIteration\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    308\u001b[0m                 \u001b[0mutil\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mupdate_params\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 309\u001b[0;31m                 \u001b[0mx_probe\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msuggest\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mutil\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    310\u001b[0m                 \u001b[0miteration\u001b[0m \u001b[0;34m+=\u001b[0m \u001b[0;36m1\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    311\u001b[0m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mprobe\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mx_probe\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mlazy\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mFalse\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.9/site-packages/bayes_opt/bayesian_optimization.py\u001b[0m in \u001b[0;36msuggest\u001b[0;34m(self, utility_function)\u001b[0m\n\u001b[1;32m    218\u001b[0m         \u001b[0;32mwith\u001b[0m \u001b[0mwarnings\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcatch_warnings\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    219\u001b[0m             \u001b[0mwarnings\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msimplefilter\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"ignore\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 220\u001b[0;31m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_gp\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfit\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_space\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mparams\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_space\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mtarget\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    221\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mis_constrained\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    222\u001b[0m                 self.constraint.fit(self._space.params,\n",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.9/site-packages/sklearn/gaussian_process/_gpr.py\u001b[0m in \u001b[0;36mfit\u001b[0;34m(self, X, y)\u001b[0m\n\u001b[1;32m    191\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    192\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mkernel_\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mrequires_vector_input\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 193\u001b[0;31m             X, y = self._validate_data(X, y, multi_output=True, y_numeric=True,\n\u001b[0m\u001b[1;32m    194\u001b[0m                                        ensure_2d=True, dtype=\"numeric\")\n\u001b[1;32m    195\u001b[0m         \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py\u001b[0m in \u001b[0;36m_validate_data\u001b[0;34m(self, X, y, reset, validate_separately, **check_params)\u001b[0m\n\u001b[1;32m    431\u001b[0m                 \u001b[0my\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mcheck_array\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0my\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mcheck_y_params\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    432\u001b[0m             \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 433\u001b[0;31m                 \u001b[0mX\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0my\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mcheck_X_y\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mX\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0my\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mcheck_params\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    434\u001b[0m             \u001b[0mout\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mX\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0my\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    435\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py\u001b[0m in \u001b[0;36minner_f\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m     61\u001b[0m             \u001b[0mextra_args\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mlen\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;34m-\u001b[0m \u001b[0mlen\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mall_args\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     62\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0mextra_args\u001b[0m \u001b[0;34m<=\u001b[0m \u001b[0;36m0\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 63\u001b[0;31m                 \u001b[0;32mreturn\u001b[0m \u001b[0mf\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     64\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     65\u001b[0m             \u001b[0;31m# extra_args > 0\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py\u001b[0m in \u001b[0;36mcheck_X_y\u001b[0;34m(X, y, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, multi_output, ensure_min_samples, ensure_min_features, y_numeric, estimator)\u001b[0m\n\u001b[1;32m    878\u001b[0m                     estimator=estimator)\n\u001b[1;32m    879\u001b[0m     \u001b[0;32mif\u001b[0m \u001b[0mmulti_output\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 880\u001b[0;31m         y = check_array(y, accept_sparse='csr', force_all_finite=True,\n\u001b[0m\u001b[1;32m    881\u001b[0m                         ensure_2d=False, dtype=None)\n\u001b[1;32m    882\u001b[0m     \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py\u001b[0m in \u001b[0;36minner_f\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m     61\u001b[0m             \u001b[0mextra_args\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mlen\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;34m-\u001b[0m \u001b[0mlen\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mall_args\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     62\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0mextra_args\u001b[0m \u001b[0;34m<=\u001b[0m \u001b[0;36m0\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 63\u001b[0;31m                 \u001b[0;32mreturn\u001b[0m \u001b[0mf\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     64\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     65\u001b[0m             \u001b[0;31m# extra_args > 0\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py\u001b[0m in \u001b[0;36mcheck_array\u001b[0;34m(array, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features, estimator)\u001b[0m\n\u001b[1;32m    718\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    719\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mforce_all_finite\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 720\u001b[0;31m             _assert_all_finite(array,\n\u001b[0m\u001b[1;32m    721\u001b[0m                                allow_nan=force_all_finite == 'allow-nan')\n\u001b[1;32m    722\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py\u001b[0m in \u001b[0;36m_assert_all_finite\u001b[0;34m(X, allow_nan, msg_dtype)\u001b[0m\n\u001b[1;32m    101\u001b[0m                 not allow_nan and not np.isfinite(X).all()):\n\u001b[1;32m    102\u001b[0m             \u001b[0mtype_err\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m'infinity'\u001b[0m \u001b[0;32mif\u001b[0m \u001b[0mallow_nan\u001b[0m \u001b[0;32melse\u001b[0m \u001b[0;34m'NaN, infinity'\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 103\u001b[0;31m             raise ValueError(\n\u001b[0m\u001b[1;32m    104\u001b[0m                     \u001b[0mmsg_err\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mformat\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    105\u001b[0m                     (type_err,\n",
      "\u001b[0;31mValueError\u001b[0m: Input contains NaN, infinity or a value too large for dtype('float64')."
     ]
    }
   ],
   "source": [
    "\n",
    "# Gradient Boosting Machine\n",
    "def gbm_cl_bo(max_depth, max_features, learning_rate, n_estimators, subsample):\n",
    "    params_gbm = {}\n",
    "    params_gbm['max_depth'] = round(max_depth)\n",
    "    params_gbm['max_features'] = max_features\n",
    "    params_gbm['learning_rate'] = learning_rate\n",
    "    params_gbm['n_estimators'] = round(n_estimators)\n",
    "    params_gbm['subsample'] = subsample\n",
    "    scores = cross_val_score(GradientBoostingClassifier(random_state=123, **params_gbm),\n",
    "                             X_cali, y_cali, scoring='accuracy', cv=5).mean()\n",
    "    score = scores.mean()\n",
    "    return score\n",
    "# Run Bayesian Optimization\n",
    "#start = time.time()\n",
    "params_gbm ={\n",
    "    'max_depth':(3, 10),\n",
    "    'max_features':(0.8, 1),\n",
    "    'learning_rate':(0.01, 1),\n",
    "    'n_estimators':(80, 150),\n",
    "    'subsample': (0.8, 1)\n",
    "}\n",
    "gbm_bo = BayesianOptimization(gbm_cl_bo, params_gbm, random_state=111)\n",
    "gbm_bo.maximize(init_points=20, n_iter=4)\n",
    "#print('It takes %s minutes' % ((time.time() - start)/60))\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "['accuracy',\n",
       " 'adjusted_mutual_info_score',\n",
       " 'adjusted_rand_score',\n",
       " 'average_precision',\n",
       " 'balanced_accuracy',\n",
       " 'completeness_score',\n",
       " 'explained_variance',\n",
       " 'f1',\n",
       " 'f1_macro',\n",
       " 'f1_micro',\n",
       " 'f1_samples',\n",
       " 'f1_weighted',\n",
       " 'fowlkes_mallows_score',\n",
       " 'homogeneity_score',\n",
       " 'jaccard',\n",
       " 'jaccard_macro',\n",
       " 'jaccard_micro',\n",
       " 'jaccard_samples',\n",
       " 'jaccard_weighted',\n",
       " 'max_error',\n",
       " 'mutual_info_score',\n",
       " 'neg_brier_score',\n",
       " 'neg_log_loss',\n",
       " 'neg_mean_absolute_error',\n",
       " 'neg_mean_absolute_percentage_error',\n",
       " 'neg_mean_gamma_deviance',\n",
       " 'neg_mean_poisson_deviance',\n",
       " 'neg_mean_squared_error',\n",
       " 'neg_mean_squared_log_error',\n",
       " 'neg_median_absolute_error',\n",
       " 'neg_root_mean_squared_error',\n",
       " 'normalized_mutual_info_score',\n",
       " 'precision',\n",
       " 'precision_macro',\n",
       " 'precision_micro',\n",
       " 'precision_samples',\n",
       " 'precision_weighted',\n",
       " 'r2',\n",
       " 'rand_score',\n",
       " 'recall',\n",
       " 'recall_macro',\n",
       " 'recall_micro',\n",
       " 'recall_samples',\n",
       " 'recall_weighted',\n",
       " 'roc_auc',\n",
       " 'roc_auc_ovo',\n",
       " 'roc_auc_ovo_weighted',\n",
       " 'roc_auc_ovr',\n",
       " 'roc_auc_ovr_weighted',\n",
       " 'top_k_accuracy',\n",
       " 'v_measure_score']"
      ]
     },
     "execution_count": 18,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "sorted(sklearn.metrics.SCORERS.keys())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [],
   "source": [
    "X_train = []\n",
    "y_train = []"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "|   iter    |  target   | learni... | max_depth | max_fe... | n_esti... | subsample |\n",
      "-------------------------------------------------------------------------------------\n"
     ]
    },
    {
     "ename": "TypeError",
     "evalue": "__init__() got an unexpected keyword argument 'random_state'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[0;32m/var/folders/k3/_2yz9lmn4qq33cbwhzsf9h8c0000gn/T/ipykernel_74018/233634406.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m     15\u001b[0m }\n\u001b[1;32m     16\u001b[0m \u001b[0mgbm_bo\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mBayesianOptimization\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mgbm_cl_bo\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mparams_gbm\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mrandom_state\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m111\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 17\u001b[0;31m \u001b[0mgbm_bo\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mmaximize\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0minit_points\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m20\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mn_iter\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m4\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.9/site-packages/bayes_opt/bayesian_optimization.py\u001b[0m in \u001b[0;36mmaximize\u001b[0;34m(self, init_points, n_iter, acquisition_function, acq, kappa, kappa_decay, kappa_decay_delay, xi, **gp_params)\u001b[0m\n\u001b[1;32m    309\u001b[0m                 \u001b[0mx_probe\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msuggest\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mutil\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    310\u001b[0m                 \u001b[0miteration\u001b[0m \u001b[0;34m+=\u001b[0m \u001b[0;36m1\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 311\u001b[0;31m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mprobe\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mx_probe\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mlazy\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mFalse\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    312\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    313\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_bounds_transformer\u001b[0m \u001b[0;32mand\u001b[0m \u001b[0miteration\u001b[0m \u001b[0;34m>\u001b[0m \u001b[0;36m0\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.9/site-packages/bayes_opt/bayesian_optimization.py\u001b[0m in \u001b[0;36mprobe\u001b[0;34m(self, params, lazy)\u001b[0m\n\u001b[1;32m    206\u001b[0m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_queue\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0madd\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mparams\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    207\u001b[0m         \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 208\u001b[0;31m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_space\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mprobe\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mparams\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    209\u001b[0m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdispatch\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mEvents\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mOPTIMIZATION_STEP\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    210\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.9/site-packages/bayes_opt/target_space.py\u001b[0m in \u001b[0;36mprobe\u001b[0;34m(self, params)\u001b[0m\n\u001b[1;32m    234\u001b[0m         \u001b[0mx\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_as_array\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mparams\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    235\u001b[0m         \u001b[0mparams\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mdict\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mzip\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_keys\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mx\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 236\u001b[0;31m         \u001b[0mtarget\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mtarget_func\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m**\u001b[0m\u001b[0mparams\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    237\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    238\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_constraint\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/var/folders/k3/_2yz9lmn4qq33cbwhzsf9h8c0000gn/T/ipykernel_74018/233634406.py\u001b[0m in \u001b[0;36mgbm_cl_bo\u001b[0;34m(max_depth, max_features, learning_rate, n_estimators, subsample, random_state)\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;31m# Linear & regression\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      2\u001b[0m \u001b[0;32mdef\u001b[0m \u001b[0mgbm_cl_bo\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mmax_depth\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mmax_features\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mlearning_rate\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mn_estimators\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0msubsample\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mrandom_state\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;36m123\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 3\u001b[0;31m     scores = cross_val_score(LinearRegression(random_state=random_state),\n\u001b[0m\u001b[1;32m      4\u001b[0m                              X_train, y_train, scoring='mse', cv=5).mean()\n\u001b[1;32m      5\u001b[0m     \u001b[0mscore\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mscores\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mmean\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py\u001b[0m in \u001b[0;36minner_f\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m     61\u001b[0m             \u001b[0mextra_args\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mlen\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;34m-\u001b[0m \u001b[0mlen\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mall_args\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     62\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0mextra_args\u001b[0m \u001b[0;34m<=\u001b[0m \u001b[0;36m0\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 63\u001b[0;31m                 \u001b[0;32mreturn\u001b[0m \u001b[0mf\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     64\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     65\u001b[0m             \u001b[0;31m# extra_args > 0\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mTypeError\u001b[0m: __init__() got an unexpected keyword argument 'random_state'"
     ]
    }
   ],
   "source": [
    "# Linear & regression\n",
    "def lin_reg(max_depth, max_features, learning_rate, n_estimators, subsample, random_state=123):\n",
    "    scores = cross_val_score(LinearRegression(random_state=random_state),\n",
    "                             X_train, y_train, scoring='neg_mean_squared_error', cv=5).mean()\n",
    "    score = scores.mean()\n",
    "    return score\n",
    "# Run Bayesian Optimization\n",
    "#start = time.time()\n",
    "\n",
    "gbm_bo = BayesianOptimization(lin_reg, params, random_state=123)\n",
    "gbm_bo.maximize(init_points=20, n_iter=4)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 88,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(20640, 8)"
      ]
     },
     "execution_count": 88,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "X_cali.shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 90,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "|   iter    |  target   | max_depth | max_fe... | min_sa... | min_we... |\n",
      "-------------------------------------------------------------------------\n",
      "| \u001b[0m1        \u001b[0m | \u001b[0m-0.6999  \u001b[0m | \u001b[0m7.875    \u001b[0m | \u001b[0m2.717    \u001b[0m | \u001b[0m2.681    \u001b[0m | \u001b[0m0.1103   \u001b[0m |\n",
      "| \u001b[0m2        \u001b[0m | \u001b[0m-0.7369  \u001b[0m | \u001b[0m8.036    \u001b[0m | \u001b[0m3.539    \u001b[0m | \u001b[0m4.942    \u001b[0m | \u001b[0m0.137    \u001b[0m |\n",
      "| \u001b[0m3        \u001b[0m | \u001b[0m-0.7462  \u001b[0m | \u001b[0m6.367    \u001b[0m | \u001b[0m3.353    \u001b[0m | \u001b[0m3.03     \u001b[0m | \u001b[0m0.1458   \u001b[0m |\n",
      "| \u001b[0m4        \u001b[0m | \u001b[0m-0.7482  \u001b[0m | \u001b[0m6.07     \u001b[0m | \u001b[0m1.358    \u001b[0m | \u001b[0m3.194    \u001b[0m | \u001b[0m0.1476   \u001b[0m |\n",
      "| \u001b[95m5        \u001b[0m | \u001b[95m-0.6906  \u001b[0m | \u001b[95m4.277    \u001b[0m | \u001b[95m2.053    \u001b[0m | \u001b[95m3.595    \u001b[0m | \u001b[95m0.1064   \u001b[0m |\n",
      "| \u001b[0m6        \u001b[0m | \u001b[0m-0.7205  \u001b[0m | \u001b[0m7.441    \u001b[0m | \u001b[0m6.097    \u001b[0m | \u001b[0m4.173    \u001b[0m | \u001b[0m0.1222   \u001b[0m |\n",
      "| \u001b[95m7        \u001b[0m | \u001b[95m-0.5935  \u001b[0m | \u001b[95m8.057    \u001b[0m | \u001b[95m2.938    \u001b[0m | \u001b[95m3.085    \u001b[0m | \u001b[95m0.04565  \u001b[0m |\n",
      "| \u001b[0m8        \u001b[0m | \u001b[0m-0.6563  \u001b[0m | \u001b[0m5.056    \u001b[0m | \u001b[0m4.786    \u001b[0m | \u001b[0m2.276    \u001b[0m | \u001b[0m0.08674  \u001b[0m |\n",
      "| \u001b[0m9        \u001b[0m | \u001b[0m-0.6141  \u001b[0m | \u001b[0m6.016    \u001b[0m | \u001b[0m3.962    \u001b[0m | \u001b[0m3.277    \u001b[0m | \u001b[0m0.06245  \u001b[0m |\n",
      "| \u001b[0m10       \u001b[0m | \u001b[0m-0.6768  \u001b[0m | \u001b[0m5.984    \u001b[0m | \u001b[0m6.36     \u001b[0m | \u001b[0m4.832    \u001b[0m | \u001b[0m0.1004   \u001b[0m |\n",
      "| \u001b[0m11       \u001b[0m | \u001b[0m-0.6595  \u001b[0m | \u001b[0m4.015    \u001b[0m | \u001b[0m3.553    \u001b[0m | \u001b[0m2.095    \u001b[0m | \u001b[0m0.0858   \u001b[0m |\n",
      "=========================================================================\n"
     ]
    }
   ],
   "source": [
    "# Random Forest Regression\n",
    "def random_forest_reg(max_depth, min_samples_split, min_weight_fraction_leaf, max_features, cv=5):\n",
    "    params = {}\n",
    "    params['max_depth'] = round(max_depth)\n",
    "    params['min_samples_split'] = int(min_samples_split)\n",
    "    params['min_weight_fraction_leaf'] = min_weight_fraction_leaf\n",
    "    #params['max_features'] = int(max_features)\n",
    "    scores = cross_val_score(RandomForestRegressor(random_state=123, **params),\n",
    "                             X_cali, y_cali, scoring='neg_mean_squared_error', cv=cv).mean()\n",
    "    score = scores.mean()\n",
    "    return score\n",
    "# Run Bayesian Optimization\n",
    "#start = time.time()\n",
    "params ={\n",
    "    'max_depth':(3, 10),\n",
    "    'min_samples_split':(2,5),\n",
    "    'min_weight_fraction_leaf':(0.0,0.2),\n",
    "    'max_features':(1, 7)\n",
    "}\n",
    "rand_for = BayesianOptimization(random_forest_reg, params, random_state=123)\n",
    "rand_for.maximize(init_points=10, n_iter=1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 91,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "{'max_depth': 8.05710367799155,\n",
       " 'max_features': 2.937753483119069,\n",
       " 'min_samples_split': 3.0853659668669424,\n",
       " 'min_weight_fraction_leaf': 0.04565264617579112}"
      ]
     },
     "execution_count": 91,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "rand_for.max['params']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 100,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "{'max_depth': None,\n",
       " 'max_features': 'auto',\n",
       " 'min_samples_split': 3,\n",
       " 'min_weight_fraction_leaf': 0.0}"
      ]
     },
     "execution_count": 100,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "best_params = rand_for.max['params']\n",
    "best_params['max_depth'] = None\n",
    "best_params['max_features'] = 'auto'\n",
    "best_params['min_samples_split'] = 3\n",
    "best_params['min_weight_fraction_leaf'] = 0.0\n",
    "best_params"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 102,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "789.1660682316478"
      ]
     },
     "execution_count": 102,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "np.square(RandomForestRegressor(**best_params).fit(X_cali,y_cali).predict(X_cali) - y_cali).sum()\n",
    "#RandomForestRegressor(**best_params).fit(X,Y).predict(X) - Y"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 94,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "{'bootstrap': True,\n",
       " 'ccp_alpha': 0.0,\n",
       " 'criterion': 'mse',\n",
       " 'max_depth': None,\n",
       " 'max_features': 'auto',\n",
       " 'max_leaf_nodes': None,\n",
       " 'max_samples': None,\n",
       " 'min_impurity_decrease': 0.0,\n",
       " 'min_impurity_split': None,\n",
       " 'min_samples_leaf': 1,\n",
       " 'min_samples_split': 2,\n",
       " 'min_weight_fraction_leaf': 0.0,\n",
       " 'n_estimators': 100,\n",
       " 'n_jobs': None,\n",
       " 'oob_score': False,\n",
       " 'random_state': None,\n",
       " 'verbose': 0,\n",
       " 'warm_start': False}"
      ]
     },
     "execution_count": 94,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#np.square(RandomForestRegressor().fit(X,Y).predict(X) - Y).sum()\n",
    "RandomForestRegressor().fit(X_cali,y_cali).get_params()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 87,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "706.6787170898199"
      ]
     },
     "execution_count": 87,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "np.square(M.predict(X_cali) - y_cali).sum()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3.9.7 ('base')",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "af4521a1c734e7c65889f479bb79ece66303508270e0aa19c37418c08bff644d"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
